language: node_js
node_js:
  - '4'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1d48355795bf25a8f9a
    on_success: change
    on_failure: always
    on_start: never
script: npm run test
after_success: cat /home/travis/build/glayzzle/grafine/coverage/lcov.info | /home/travis/build/glayzzle/grafine/node_modules/coveralls/bin/coveralls.js
